apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  DB_HOST: {{  .Values.app.dbconfig.host | b64enc}}
  DB_PORT: {{  .Values.app.dbconfig.port | b64enc}}
  DB_USER: {{  .Values.app.dbconfig.user | b64enc}}
  DB_PASSWORD: {{  .Values.app.dbconfig.password | b64enc}}
  DB_SCHEMA: {{  .Values.app.dbconfig.schema | b64enc}}
  DB_NAME: {{  .Values.app.dbconfig.name | b64enc}}
  MANUFACTURE_USER: {{ .Values.app.appconfig.MANUFACTURE_USER | b64enc}}
  MANUFACTURE_PASSWORD: {{ .Values.app.appconfig.MANUFACTURE_PASSWORD | b64enc}}

