name: Build and push to Dockerhub

on:
  push:
    branches: [ master, migrateToPsql ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.TC_SHOWCASE_DOCKERHUB_USER }}
        password: ${{ secrets.TC_SHOWCASE_DOCKERHUB_PASSWORD }}
        repository: novatec/technologyconsulting-showcase-supplierdomain
        tags: latest, ${{ env.SHORT_SHA }} 
        tag_with_sha: true
    
    - name: Run Trivy vulnerability scanner MEDIUM,HIGH
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'novatec/technologyconsulting-showcase-orderdomain:${{ env.SHORT_SHA }}'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        exit-code: 0
        ignore-unfixed: false
        severity: MEDIUM,HIGH
    
    - name: Run Trivy vulnerability scanner CRITICAL
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'novatec/technologyconsulting-showcase-orderdomain:${{ env.SHORT_SHA }}'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        exit-code: 1
        ignore-unfixed: false
        severity: CRITICAL  
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'